language: php
php:
 - 7.2

env:
  global:
    - PATH="${HOME}/build/thunder/thunder-admin-tests/scripts:${HOME}/build/test-dir/bin:$PATH"
  matrix:
    - SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_BRANCH=next
    - SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_BRANCH=current
    - SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_CORE="~8.6.1"
    - SHARPEYE_BROWSER=chrome
    - SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_BRANCH=next
    - SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_BRANCH=current
    - SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_CORE="~8.6.1"
    - SHARPEYE_BROWSER=firefox

matrix:
  allow_failures:
    - env: SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_BRANCH=next
    - env: SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_BRANCH=current
    - env: SHARPEYE_BROWSER=chrome THUNDER=8.x-2.x DRUPAL_CORE="~8.6.1"
    - env: SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_BRANCH=next
    - env: SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_BRANCH=current
    - env: SHARPEYE_BROWSER=firefox THUNDER=8.x-2.x DRUPAL_CORE="~8.6.1"

dist:
  - xenial

branches:
  only:
    - /[0-9]+\.x/

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.cache/yarn"

services:
  - mysql

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/sharpeye
  apt:
    packages:
      - graphicsmagick

before_install:
  - git clone --depth 1 https://github.com/BurdaMagazinOrg/theme-thunder-admin.git -b 8.x-2.x ${HOME}/build/BurdaMagazinOrg/theme-thunder-admin
  - source determine-drupal-versions.sh
  - before-install.sh

install:
  - install.sh

before_script:
  - before-script.sh

script:
  - build.sh
  - visual.sh
