language: php
sudo: false
php: 7.1

env:
  global:
    - PATH="${HOME}/build/thunder/thunder-admin-tests/scripts:${HOME}/build/test-dir/bin:$PATH"
  matrix:
    - SHARPEYE_BROWSER=chrome THUNDER=develop DRUPAL=next
    - SHARPEYE_BROWSER=chrome THUNDER=develop DRUPAL=current
    - SHARPEYE_BROWSER=chrome THUNDER=feature/2908887-paragraphs-experimental
    - SHARPEYE_BROWSER=chrome
    - SHARPEYE_BROWSER=firefox THUNDER=develop DRUPAL=next
    - SHARPEYE_BROWSER=firefox THUNDER=develop DRUPAL=current
    - SHARPEYE_BROWSER=firefox
    - SHARPEYE_BROWSER=firefox THUNDER=feature/2908887-paragraphs-experimental

matrix:
  allow_failures:
    - env: SHARPEYE_BROWSER=firefox THUNDER=develop DRUPAL=next
    - env: SHARPEYE_BROWSER=chrome THUNDER=develop DRUPAL=next

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.cache/yarn"

services:
  - docker

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/sharpeye
  apt:
    packages:
      - graphicsmagick

before_install:
  - git clone --depth 1 https://github.com/BurdaMagazinOrg/theme-thunder-admin.git -b 8.x-2.x ${HOME}/build/BurdaMagazinOrg/theme-thunder-admin
  - source determine-drupal-versions.sh
  - before-install.sh

install:
  - install.sh

before_script:
  - before-script.sh

script:
  - build.sh
  - visual.sh
