language: php
sudo: false
php: 7.1

env:
#  - SHARPEYE_BROWSER=chrome
  - SHARPEYE_BROWSER=firefox

branches:
  only:
    - master

#cache:
#  apt: true
#  directories:
#    - "$HOME/.composer/cache"
#    - "$HOME/.drush/cache"

#services:
#  - docker

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/sharpeye
  apt:
    packages:
      - graphicsmagick

before_install:
  - bash -x -e ./scripts/before-install.sh

install:
  - bash -x -e ./scripts/install.sh