language: php
sudo: false
php: 7.1

env:
  global:
    -THUNDER=`echo ${TRAVIS_BUILD_DIR}"/../thunder"`
    -THEME=`echo ${THUNDER}"/docroot/themes/contrib/thunder_admin/"`
    -PATH="$THUNDER/bin:$PATH"
  matrix:
    - SHARPEYE_BROWSER=chrome
    - SHARPEYE_BROWSER=firefox

branches:
  only:
    - master

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

services:
  - docker

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/sharpeye
  apt:
    packages:
      - graphicsmagick

before_install:
  - bash -x -e ./scripts/before-install.sh

install:
  - bash -x -e ./scripts/install.sh

before_script:
  - bash -x -e ./scripts/before-script.sh

script:
  - bash -x -e ./scripts/build.sh
  - bash -x -e ./scripts/visual.sh
